collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
author:
  name: Abhay Rana
  url: https://about.me/n3m0
title: Abhay Rana
tagline: aka Capt. Nemo
description: |
  <div class="image">
    <img class="thumbnail" src="/img/profile.jpg">
  </div>
url: https://captnemo.in
baseurl: /
paginate: 3
paginate_path: "/page/:num/"
gems:
  - jekyll-paginate